parameters:
#    sifo_shared.example.class: Sifo\SharedBundle\Example

services:
#    sifo_shared.example:
#        class: %sifo_shared.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
