Sifo\SharedBundle\Entity\BlogPage:
    type: entity
    repositoryClass: Sifo\AdminBundle\Repository\BlogPageRepository
    table: blogpage
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        tittle:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
        content:
            type: text
            nullable: true
            fixed: false
            comment: ''
            default: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: ''
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        operator:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: ''
    oneToMany:
        blogMenus:
            targetEntity: BlogMenu
            mappedBy: blogPage
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]