Sifo\SharedBundle\Entity\BlogCategory:
    type: entity
    repositoryClass: Sifo\AdminBundle\Repository\BlogCategoryRepository
    table: blogcategory
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
        description:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            default: ''
        orders:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: ''
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        operator:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: ''
    oneToMany:
        blogMenus:
            targetEntity: BlogMenu
            mappedBy: blogCategory
    manyToMany:
        blogArticles:
            targetEntity: BlogArticle
            mappedBy: blogCategories
        blogAgendas:
            targetEntity: BlogAgenda
            mappedBy: blogCategories
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]