Sifo\SharedBundle\Entity\Position:
    type: entity
    repositoryClass: Sifo\AdminBundle\Repository\PositionRepository
    table: position
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            default: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: ''
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        operator:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: ''
    oneToMany:
        employees:
            targetEntity: Employee
            mappedBy: position
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]