Sifo\SharedBundle\Entity\SubjectsGrouping:
    type: entity
    table: subjects_grouping
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        category:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: ''
        day:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        startTime:
            type: time
            nullable: true
            column: start_time
        endTime:
            type: time
            nullable: true
            column: end_time
        description:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
            default: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: ''
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        operator:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: ''
    manyToOne:
        grouping:
            targetEntity: Grouping
            inversedBy: subjectsGroupings
            joinColumns:
                grouping_id:
                    nullable: false
                    referencedColumnName: id
        subject:
            targetEntity: Subject
            inversedBy: subjectsGroupings
            joinColumns:
                subject_id:
                    nullable: false
                    referencedColumnName: id
        employee:
            targetEntity: Employee
            inversedBy: subjectsGroupings
            joinColumns:
                employee_id:
                    nullable: false
                    referencedColumnName: id
    oneToMany:
        results:
            targetEntity: Result
            mappedBy: subjectsGrouping
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]