parameters:
#    sifo_admin.example.class: Sifo\AdminBundle\Example

services:
#    sifo_admin.example:
#        class: %sifo_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
