admin_master_student:
    pattern:  /index.php
    defaults: { _controller: "SifoAdminBundle:Student:index" }

admin_master_student_filter:
    pattern:  /filter/index.php
    defaults: { _controller: "SifoAdminBundle:Student:filter" }

admin_master_student_show:
    pattern:  /{id}/show/index.php
    defaults: { _controller: "SifoAdminBundle:Student:show" }

admin_master_student_new:
    pattern:  /new/index.php
    defaults: { _controller: "SifoAdminBundle:Student:new" }

admin_master_student_create:
    pattern:  /create/index.php
    defaults: { _controller: "SifoAdminBundle:Student:create" }
    requirements: { _method: post }

admin_master_student_edit:
    pattern:  /{id}/edit/index.php
    defaults: { _controller: "SifoAdminBundle:Student:edit" }

admin_master_student_update:
    pattern:  /{id}/update/index.php
    defaults: { _controller: "SifoAdminBundle:Student:update" }
    requirements: { _method: post|put }

admin_master_student_update_password:
    pattern:  /{id}/update-password/index.php
    defaults: { _controller: "SifoAdminBundle:Student:password" }
    requirements: { _method: post|put }

admin_master_student_remove:
    pattern:  /{id}/remove/index.php
    defaults: { _controller: "SifoAdminBundle:Student:remove" }

admin_master_student_delete:
    pattern:  /{id}/delete/index.php
    defaults: { _controller: "SifoAdminBundle:Student:delete" }
    requirements: { _method: post|delete }
