parameters:
#    sifo_user.example.class: Sifo\UserBundle\Example

services:
#    sifo_user.example:
#        class: %sifo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
